INSERT into TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (100001, 'SanDevil23',  'abcdef', CURRENT_DATE(), false);

INSERT into TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (100002, 'SanDevil23',  'xyz', CURRENT_DATE(), false);

INSERT into TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (100003, 'SanDevil23',  'mnjo', CURRENT_DATE(), false);

INSERT into TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (100004, 'SanDevil23',  'llps', CURRENT_DATE(), false);

INSERT into TODO (ID,USERNAME,DESCRIPTION,TARGET_DATE,DONE)
values (100005, 'SanDevil23',  'guu', CURRENT_DATE(), false);